### ISSUE TITLE
Cannot open the editor

### ISSUE THREAD

**Issue by lmhitchcock1** [Estivoo/csv-editor#1]
Hi, 
I have downloaded the extension, but I cannot figure out how to edit a file with it. Is there a specific way to edit a csv via your extension? If so please provides steps, and possibly add them to the instructions. Thanks in advance.

**Comment by Estivoo** [comment]
Hey,
I thought I recorded how to open it in one of gifs with possibilities. To open it you just have to use command palette - ctrl + shift + p - and type - Simple CSV Editor - and hit enter. Currently I'm away from home. I will add a button like some of other similar plugins if you want :) Also I will update README.

It's nice to know that not only my friends downloaded this plugin :D Thanks.

**Comment by lmhitchcock1** [comment]
It worked! Thank you so much for the help and for building this.
