### ISSUE TITLE
Could you support other separator character?

### ISSUE THREAD

**Issue by pakLebah** [Estivoo/csv-editor#3]
First of all, thank you for making this useful extension. Some people might got surprised to know that CSV format is still being used everywhere all over the world. It's the most common data format in the world, even today. Almost any spreadsheet applications can read and manage them.

Although the name is known as Comma Separated Values (CSV) but there are other separator characters commonly used as well for .csv files. They are semicolon (`;`) and tab (`⇥`) characters. It seems that your extension only supports comma (`,`) and nothing else. So, could you please provide support for other common separator as well? If you could support arbitrary separator characters (through config), that'd be a lot better.

Because I'm here having tons of .csv files that are using three of them (depend from where they come from), and sometimes they also use `|` for separator. Your extension helps me manage those file easier and faster rather than using bloated modern spreadsheet applications. We don't need those fancy data formats (xlsx) for large of simple datum. CSV is lightweight, fast, dan small.

Thank you.

**Comment by Estivoo** [comment]
Hey, sorry for delay. I'm on it :)

**Comment by Estivoo** [comment]
Hey @pakLebah, I pushed new package to store. Now plugin will try to predict used delimiter, if it fails then you will be asked to type delimiter which is used. Plugin checks all characters which you mentioned in your suggestion.

One thing is that tabs mixed with multiline fields are only working good with quotation marks.

New package should be live already ;) Let me know if those changes makes your life easier and if everything is working. I will not close this issue yet.

I'm glad to hear that someone is using this. Thanks a lot.

**Comment by pakLebah** [comment]
Thank you. It now works with all separators I need. 👍
